config/routes.rb
CraftApp::Application.routes.draw do
  get "crafts/index"

  get "crafts/show"

  get "crafts/new"

  get "crafts/destroy"

  get "crafts/create"

  get "crafts/edit"

  get "crafts/update"

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :practices, only: [:new, :create, :destroy]
  resources :crafts, only: [:index, :new, :create, :destroy]

  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  root to: 'static_pages#home'

  match '/signup',  to: 'users#new'
  match '/about',   to: 'static_pages#about'

end

app/models/craft.rb
# == Schema Information
#
# Table name: crafts
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Craft < ActiveRecord::Base
  attr_accessible :name
  has_many :practices

  validates :name, presence: true
end

app/models/practice.rb
# == Schema Information
#
# Table name: practices
#
#  id         :integer          not null, primary key
#  user_id    :integer
#  craft_id   :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Practice < ActiveRecord::Base
  attr_accessible :craft_id
  belongs_to :user
  belongs_to :craft

  validates :user_id,  presence: true # will always be created through user
  validates :craft_id, presence: true

  validates_uniqueness_of :craft_id,  scope: :user_id
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  name            :string(255)
#  email           :string(255)
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  password_digest :string(255)
#  remember_token  :string(255)
#  admin           :boolean          default(FALSE)
#

class User < ActiveRecord::Base
  attr_accessible :email, :name, :password, :password_confirmation
  has_secure_password
  has_many :practices, dependent: :destroy
  has_many :crafts, through: :practices, source: :user

  before_save { |user| user.email = email.downcase }
  before_save :create_remember_token  

  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }

  validates :password, presence: true, length: { minimum: 6 }
  validates :password_confirmation, presence: true



  private

    def create_remember_token
      self.remember_token = SecureRandom.urlsafe_base64
    end  
                   
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper

  # Force signout to prevent CSRF attacks
  def handle_unverified_request
    sign_out
    super
  end
end

app/controllers/crafts_controller.rb
class CraftsController < ApplicationController
  before_filter :admin_user

  def index  
    @crafts = Craft.paginate(page: params[:page])
  end

  def new
    @craft = Craft.new
  end

  def destroy
    Craft.find(params[:id]).destroy
    flash[:success] = "Craft destroyed."
    redirect_to crafts_path
  end

  def create
    @craft = Craft.new(params[:craft])
      if @craft.save
        flash[:success] = "Craft added"
        redirect_to crafts_path
      else
        render 'new'
      end
  end

end

app/controllers/practices_controller.rb
class PracticesController < ApplicationController
	before_filter :signed_in_user, only: [:create, :destroy]

	def create
		@practice = current_user.practices.build(params[:practice])
		if @practice.save
			flash[:success] = "Practice Created!"
			redirect_to user_path(current_user)
		else
			render 'new'
		end			
	end

	def destroy
		Practice.find(params[:id]).destroy
		flash[:success] = "Practice destroyed."
		redirect_to user_path(current_user)
	end

	def new	
		@practice = current_user.practices.build
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      sign_in user
      redirect_back_or user
    else
      flash.now[:error] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
		if signed_in?
			redirect_to user_path(current_user)
		end
  end

  def about
  end  

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :signed_in_user, only: [:index, :edit, :update, :destroy]
  before_filter :correct_user,   only: [:edit, :update]
  before_filter :admin_user,     only: :destroy


  def index
    @users = User.paginate(page: params[:page])
  end

  def show
    @user = User.find(params[:id])
    @practices = @user.practices.paginate(page: params[:page])
  end
  	
  def new
    @user = User.new  	
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User destroyed."
    redirect_to users_url
  end  

  def create
    @user = User.new(params[:user])
    if @user.save
      sign_in @user
      flash[:success] = "Welcome to the Sample App!"
      redirect_to @user
    else
      render 'new'
    end
  end  

  def edit
    #user found by correct user
  end

  def update
    #user found by correct user
    if @user.update_attributes(params[:user])
      flash[:success] = "Profile updated"
      sign_in @user
      redirect_to @user
    else
      render 'edit'
    end
  end

  private

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_path) unless current_user?(@user)
    end  


end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "Ruby on Rails Tutorial Sample App"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/crafts_helper.rb
module CraftsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    cookies.permanent[:remember_token] = user.remember_token
    self.current_user = user
  end

  def signed_in?
    !current_user.nil?
  end  

  def current_user=(user)
    @current_user = user
  end  

  def current_user
    @current_user ||= User.find_by_remember_token(cookies[:remember_token])
  end  

  def current_user?(user)
    user == current_user
  end  

  def admin_user
    redirect_to(root_path) unless current_user.admin?
  end        

  def signed_in_user
    unless signed_in?
      store_location
      redirect_to signin_url, notice: "Please sign in."
    end
  end  

  def sign_out
    self.current_user = nil
    cookies.delete(:remember_token)
  end

  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end

  def store_location
    session[:return_to] = request.url
  end  
    
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  # Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(user, options = { size: 50 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/crafts/_craft.html.erb
<li>
  <%= craft.name %>    
  <%= link_to "delete", craft, method: :delete,
                               data: { confirm: "You sure?" }%>
</li>  

app/views/crafts/index.html.erb
<% provide(:title, 'All crafts') %>
<h1>All crafts</h1>

<ul class="crafts">
	<%= render @crafts %>
</ul>

 <%= link_to "Add Craft", crafts_new_path %> 

app/views/crafts/new.html.erb
<h1> Add new craft </h1>
<div class="row">
<aside class="span4">
  <section>
    <%= form_for(@craft) do |f| %>
			<%= render 'shared/error_messages', object: f.object %>
			<div class = "field">
	      <%= f.label :name %>
	      <%= f.text_field :name %>	     
	    </div>
	    <%= f.submit "Post", class: "btn btn-large btn-primary" %>
		<% end %>
  </section>
</aside>
</div>  

app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav>
    <ul>
      <li><%= link_to "Find out about crafters",   about_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "crafters", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home", root_path %></li>
          <!-- <li><%= link_to "About", about_path %></li> -->
          <% if signed_in? %>
            <li><%= link_to "Users", users_path %></li>

            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Sign out", signout_path, method: "delete" %>
                </li>
              </ul>
            </li>
            <% if current_user.admin? %>
              <li><%= link_to "Crafts", crafts_path %></li> 
            <% end %>
          <% else %>
            <li><%= link_to "Sign in", signin_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>    
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>
      <%# render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/practices/_practice.html.erb
<% if Craft.find_by_id(practice.craft_id) %>
	<li>
	  <span class = "practice"><%= practice.craft.name %></span>
	  <% if current_user?(practice.user) %>
	    <%= link_to "delete", practice, method: :delete,
	                                    data: { confirm: "You sure?" }%>
	  <% end %>	
	</li>
<% end %>

app/views/practices/new.html.erb
<div class="row">
<aside class="span4">
  <section>

    <%= form_for(@practice) do |f| %>
			<%= render 'shared/error_messages', object: f.object %>
	    <div class = "field">
		  <%= f.label "Craft" %>		
	      <%= f.select :craft_id,  Craft.all.map{ |x| [x.name, x.id]  }%>
	    </div>
	    <%= f.submit "Post", class: "btn btn-large btn-primary" %>
		<% end %>
  </section>
</aside>
</div>   

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, 'About Us') %>
<h1>About Us</h1>
<p>
	Craft App about
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
	This is not need
</p>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<h1>Help</h1>
<p>
	This is not needed
</p>

app/views/static_pages/home.html.erb
<div class="center hero-unit">
  <h2>
  	 Do something?
  </h2>
  <%= link_to "Sign up now!", signup_path, class: "btn btn-large btn-primary" %>
</div>

app/views/users/_user.html.erb
<li>
  <%# gravatar_for user, size: 52 %>
  <%= link_to user.name, user %>
  <% if current_user.admin? && !current_user?(user) %>
    | <%= link_to "delete", user, method: :delete,
                                  data: { confirm: "You sure?" } %>
  <% end %>
</li>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update your profile</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirm Password" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
    <% end %>

    <%= gravatar_for @user %>
    <a href="http://gravatar.com/emails">change</a>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>

<%= will_paginate %>

<ul class="users">
	<%= render @users %>
</ul>


<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="span4">
    <section>
      <h1>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
  <div class = "span8">
  	<% if @user.practices.any? %>
    	<h3> Practices (<%= @user.practices.count %>) </h3>
    	<ol class = "practices">
    		<%= render @practices %>
    	</ol>
    	<%= will_paginate @practices %>
  	<% end %>
    <%= link_to "Add Practice", new_practice_path  if current_user?(@user)%> 
  </div> 
</div>